service: new-goods-get

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stage: prod

package:
  exclude:
    - .serverless/**
    - .vscode/**
    - src/**
    - .gitignore
    - package.json
    - package-lock.json
    - tsconfig.json
    - README.md

functions:
  func:
    handler: dist/lambda.handler
